---
AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudfront-ed S3 Bucket
Parameters:
  WebsiteName:
    Type: String
    Description: E.g. the "www" in www.example.com
  BucketName:
    Type: String
    Default: ""
    Description: If not supplied, a bucket will be created and named after the stack
  DomainName:
    Type: String
    Description: E.g. "example.com" in www.example.com
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: You must already have a Hosted Zone setup for your domain in Route53.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: DNS
        Parameters:
          - HostedZoneId
          - WebsiteName
          - DomainName
      - Label:
          default: Optional
        Parameters:
          - BucketName
    ParameterLabels:
      BucketName:
        default: Existing S3 Bucket Name
      DomainName:
        default: Domain Name
      WebsiteName:
        default: Website Name
      HostedZoneId:
        default: Hosted Zone Id
Conditions:
  BucketNameEmpty: !Equals [!Ref BucketName, ""]
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub ${WebsiteName}.${DomainName}
      DomainValidationOptions:
        - DomainName: !Sub ${WebsiteName}.${DomainName}
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: Simple Website Origin Access Control
        Description: OAC for Simple Website
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  ARecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt DistributionCloudFrontNet.DomainName
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub ${WebsiteName}.${DomainName}
      Type: A
  AAAARecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt DistributionCloudFrontNet.DomainName
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub ${WebsiteName}.${DomainName}
      Type: AAAA
  HTML:
    Type: AWS::S3::Bucket
    Condition: BucketNameEmpty
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: !Sub ${WebsiteName}.${DomainName}
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub ${AWS::StackName}-security-headers
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
  DistributionCloudFrontNet:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${WebsiteName}.${DomainName}
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
        CacheBehaviors:
          - PathPattern: "*.css"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.js"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.jpg"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.jpeg"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.png"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.gif"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.ico"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.svg"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.woff"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.woff2"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.ttf"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          - PathPattern: "*.webp"
            TargetOriginId:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        DefaultCacheBehavior:
          TargetOriginId:
            !If [
              BucketNameEmpty,
              !Sub "S3-origin-${HTML}",
              !Sub "S3-origin-${BucketName}",
            ]
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy
        Origins:
          - DomainName:
              !If [
                BucketNameEmpty,
                !GetAtt HTML.RegionalDomainName,
                !Sub "${BucketName}.s3.us-east-1.amazonaws.com",
              ]
            Id:
              !If [
                BucketNameEmpty,
                !Sub "S3-origin-${HTML}",
                !Sub "S3-origin-${BucketName}",
              ]
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        Restrictions:
          GeoRestriction:
            RestrictionType: none
            Locations: []
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
          AcmCertificateArn: !Ref Certificate
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !If [
                BucketNameEmpty,
                !Ref HTML,
                !Ref BucketName,
              ]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !If [
                BucketNameEmpty,
                !Sub "arn:aws:s3:::${HTML}/*",
                !Sub "arn:aws:s3:::${BucketName}/*",
              ]
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionCloudFrontNet}"
Outputs:
  Route53URL:
    Value: !Sub https://${ARecordSet}
    Description: Simple website URL (remember to put some HTML in the S3 bucket)
  CloudFrontURL:
    Value: !GetAtt DistributionCloudFrontNet.DomainName
    Description: CloudFront URL
  Upload:
    Value: !If [
                BucketNameEmpty,
                !Sub "aws s3 cp index.html s3://${HTML}",
                !Sub "aws s3 cp index.html s3://${BucketName}",
              ]
    Description: Upload your first file
